server:
  port: 8080
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  servlet:
    context-path: /api

spring:
  application:
    name: hackernews-backend

webclient:
  urls:
    hacker-news:
      https://hacker-news.firebaseio.com/v0

